# on:
jobs:
  build: 
    runs-on: ubuntu-20.04 
    # which machine/environ like Ubuntu or so
    steps:
      # first pull in code to start
      - uses: actions/checkout@v2
      # now with the code, we can build
      - run: dotnet build

      # test: xunit + coverlet
      # analyze: sonarcloud (static code anaylsis)

name: ci-pipeline
trigger: push
